/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bangumi/': RouteRecordInfo<
      '/bangumi/',
      '/bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/pixiv/': RouteRecordInfo<
      '/pixiv/',
      '/pixiv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Godot大学习/一些Godot插件推荐': RouteRecordInfo<
      '/posts/Godot大学习/一些Godot插件推荐',
      '/posts/Godot%E5%A4%A7%E5%AD%A6%E4%B9%A0/%E4%B8%80%E4%BA%9BGodot%E6%8F%92%E4%BB%B6%E6%8E%A8%E8%8D%90',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/ShaderLab（USL）': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/ShaderLab（USL）',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/ShaderLab%EF%BC%88USL%EF%BC%89',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter10': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter10',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter11': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter11',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter6': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter6',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter7': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter7',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter8': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter8',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader入门精要URP重置/UnityShader-Chapter9': RouteRecordInfo<
      '/posts/Shader入门精要URP重置/UnityShader-Chapter9',
      '/posts/Shader%E5%85%A5%E9%97%A8%E7%B2%BE%E8%A6%81URP%E9%87%8D%E7%BD%AE/UnityShader-Chapter9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/UnityShader/PBR基础': RouteRecordInfo<
      '/posts/UnityShader/PBR基础',
      '/posts/UnityShader/PBR%E5%9F%BA%E7%A1%80',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/bangumi/index.md': {
      routes:
        | '/bangumi/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/pixiv/index.md': {
      routes:
        | '/pixiv/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Godot大学习/一些Godot插件推荐.md': {
      routes:
        | '/posts/Godot大学习/一些Godot插件推荐'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/ShaderLab（USL）.md': {
      routes:
        | '/posts/Shader入门精要URP重置/ShaderLab（USL）'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter10.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter10'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter11.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter11'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter6.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter6'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter7.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter7'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter8.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter8'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Shader入门精要URP重置/UnityShader-Chapter9.md': {
      routes:
        | '/posts/Shader入门精要URP重置/UnityShader-Chapter9'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/UnityShader/PBR基础.md': {
      routes:
        | '/posts/UnityShader/PBR基础'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
